server:
  port: 8761

spring:
  application:
    name: discoveryserver
  cloud:
    config:
      uri: http://127.0.0.1:8889
      nane: kkoch

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
